/* Scene catalog: the single source of truth for the system hierarchy.
 * Scene files implement these ids via Atlas.register({ id, steps, ... }).
 * Order inside a parent = order here. Levels: 0 = whole system, 1 = subsystem,
 * 2 = component, 3 = primitive. */
window.ATLAS_CATALOG = [
  { id: 'overview', parent: null, level: 0, file: '00-overview.js', color: 'cyan',
    title: 'The Whole Machine', kicker: 'End-to-end architecture',
    summary: 'A single prompt becomes a finished film: client, gateway, orchestration, agents, models, GPU cluster and delivery.' },

  { id: 'client', parent: 'overview', level: 1, file: '10-client.js', color: 'cyan',
    title: 'Client & Real-time Transport', kicker: 'User device to cloud',
    summary: 'Resumable uploads, streaming protocols (SSE / WebSocket / WebRTC), auth, optimistic UI and progress streaming.' },
  { id: 'gateway', parent: 'overview', level: 1, file: '11-gateway.js', color: 'blue',
    title: 'Edge, Gateway & Admission Control', kicker: 'Anycast to API',
    summary: 'Anycast/GeoDNS, TLS termination, auth, rate limiting, quota and admission control before any GPU is touched.' },
  { id: 'orchestration', parent: 'overview', level: 1, file: '20-orchestration.js', color: 'magenta',
    title: 'AI Orchestration Plane', kicker: 'The control brain',
    summary: 'Turns intent into a plan: a DAG of agent tasks executed by a durable workflow engine with state, events and human-in-the-loop.' },
  { id: 'agent-loop', parent: 'orchestration', level: 2, file: '21-agent-loop.js', color: 'magenta',
    title: 'The Agent Loop: from LLM to Agent', kicker: 'Observe · Think · Act',
    summary: 'How a next-token predictor becomes an agent: context assembly, reasoning, tool calls, observations, stop conditions, compaction.' },
  { id: 'tool-calling', parent: 'orchestration', level: 2, file: '22-tool-calling.js', color: 'magenta',
    title: 'Tool Calling & MCP', kicker: 'Structured action',
    summary: 'JSON-Schema tools, constrained decoding, parallel calls, Model Context Protocol, sandboxes and error recovery.' },
  { id: 'multi-agent', parent: 'orchestration', level: 2, file: '23-multi-agent.js', color: 'magenta',
    title: 'Multi-Agent Collaboration', kicker: 'A film crew of agents',
    summary: 'Director, writer, storyboard, cinematographer, editor and critic agents: supervisor topologies, handoffs, shared blackboard.' },
  { id: 'durable-exec', parent: 'orchestration', level: 2, file: '24-durable.js', color: 'magenta',
    title: 'Durable Workflow Execution', kicker: 'Never lose a render',
    summary: 'Event-sourced workflows, deterministic replay, retries with backoff, idempotency, sagas and checkpointing of long GPU jobs.' },

  { id: 'multimodal', parent: 'overview', level: 1, file: '30-multimodal.js', color: 'violet',
    title: 'Multimodal Understanding', kicker: 'Pixels, audio, text to tokens',
    summary: 'How images, video clips and audio uploaded by the user become tokens an LLM can reason over.' },
  { id: 'vision-encoder', parent: 'multimodal', level: 2, file: '31-vision.js', color: 'violet',
    title: 'Vision Encoders & Visual Tokens', kicker: 'ViT, patches, projectors',
    summary: 'Patchify, ViT, native-resolution packing, temporal frame sampling, token compression and the projector into LLM space.' },
  { id: 'audio-encoder', parent: 'multimodal', level: 2, file: '32-audio-enc.js', color: 'violet',
    title: 'Audio & Speech Encoding', kicker: 'Waveform to tokens',
    summary: 'Log-mel spectrograms, Whisper-style encoders, neural audio codecs (RVQ) and discrete audio tokens.' },
  { id: 'contrastive', parent: 'multimodal', level: 2, file: '33-contrastive.js', color: 'violet',
    title: 'Contrastive Alignment', kicker: 'CLIP / SigLIP',
    summary: 'Learning a shared embedding space for text and images with contrastive losses; the backbone of retrieval and conditioning.' },

  { id: 'llm', parent: 'overview', level: 1, file: '40-llm.js', color: 'amber',
    title: 'Inside the LLM', kicker: 'The reasoning engine',
    summary: 'Tokens to embeddings to a deep stack of transformer blocks to logits: the autoregressive machine at the core of every agent.' },
  { id: 'tokenization', parent: 'llm', level: 2, file: '41-tokens.js', color: 'amber',
    title: 'Tokenization & Embeddings', kicker: 'Text to vectors',
    summary: 'Byte-level BPE, vocabularies, embedding lookup and the geometry of the residual stream.' },
  { id: 'transformer', parent: 'llm', level: 2, file: '42-transformer.js', color: 'amber',
    title: 'The Transformer Block', kicker: 'Residual stream machinery',
    summary: 'Pre-norm residual blocks: RMSNorm, attention, SwiGLU MLP, RoPE, and why depth composes circuits.' },
  { id: 'neuron', parent: 'transformer', level: 3, file: '46-neuron.js', color: 'amber',
    title: 'A Single Neuron', kicker: 'The atom of computation',
    summary: 'Weighted sum, bias, nonlinearity, gradient descent and backprop, then how millions of neurons become one matmul on a tensor core.' },
  { id: 'moe', parent: 'transformer', level: 3, file: '47-moe.js', color: 'amber',
    title: 'Mixture of Experts', kicker: 'Sparse capacity',
    summary: 'Top-k routers, load-balancing losses, fine-grained and shared experts, capacity factors and expert parallel all-to-all.' },
  { id: 'attention', parent: 'llm', level: 2, file: '43-attention.js', color: 'amber',
    title: 'Attention, Up Close', kicker: 'softmax(QK^T/sqrt(d))V',
    summary: 'Queries, keys, values, causal masks, multi-head, GQA and MLA, and the KV cache that makes decoding fast.' },
  { id: 'flash-attention', parent: 'attention', level: 3, file: '48-flash.js', color: 'amber',
    title: 'FlashAttention', kicker: 'IO-aware kernels',
    summary: 'Tiling, online softmax, SRAM vs HBM traffic, and why attention is memory-bound rather than compute-bound.' },
  { id: 'decoding', parent: 'llm', level: 2, file: '45-decoding.js', color: 'amber',
    title: 'Decoding & Structured Output', kicker: 'Logits to actions',
    summary: 'Temperature, top-p, grammar-constrained decoding for tool JSON, and speculative decoding.' },
  { id: 'training', parent: 'llm', level: 2, file: '44-training.js', color: 'amber',
    title: 'How an LLM Learns to Be an Agent', kicker: 'Pretrain · SFT · RL',
    summary: 'Pretraining, instruction tuning, preference optimization and RL with verifiable rewards on multi-step tool-use trajectories.' },

  { id: 'videogen', parent: 'overview', level: 1, file: '50-videogen.js', color: 'lime',
    title: 'Video Generation Models', kicker: 'Noise to motion',
    summary: 'Latent diffusion / flow-matching transformers that generate spatiotemporal latents conditioned on text, images and audio.' },
  { id: 'diffusion', parent: 'videogen', level: 2, file: '51-diffusion.js', color: 'lime',
    title: 'Diffusion & Flow Matching', kicker: 'Learning to denoise',
    summary: 'Forward noising, score / velocity prediction, rectified flow ODEs, samplers, classifier-free guidance and few-step distillation.' },
  { id: 'video-vae', parent: 'videogen', level: 2, file: '52-vae.js', color: 'lime',
    title: 'Spatiotemporal VAE', kicker: 'Compressing video',
    summary: 'Causal 3D convolutional VAEs, compression ratios, latent channels and why they decide what the generator can afford.' },
  { id: 'dit', parent: 'videogen', level: 2, file: '53-dit.js', color: 'lime',
    title: 'Diffusion Transformer (DiT)', kicker: 'Spacetime patches',
    summary: '3D patch tokens, full spatiotemporal attention, 3D RoPE, adaLN timestep modulation and text cross-attention / MM-DiT.' },
  { id: 'consistency', parent: 'videogen', level: 2, file: '54-control.js', color: 'lime',
    title: 'Control, Consistency & Long Video', kicker: 'Directing the model',
    summary: 'Reference images, identity preservation, camera control, keyframes, autoregressive extension and shot-to-shot continuity.' },

  { id: 'postprod', parent: 'overview', level: 1, file: '60-postprod.js', color: 'orange',
    title: 'Audio, Editing & Delivery', kicker: 'From clips to a film',
    summary: 'Voice, music and sound effects, lip-sync, timeline assembly, upscaling, encoding and adaptive streaming.' },
  { id: 'tts-audio', parent: 'postprod', level: 2, file: '61-audio-gen.js', color: 'orange',
    title: 'Speech, Music & Lip-Sync', kicker: 'Generative audio',
    summary: 'Codec-language-model TTS, flow-matching music, video-to-audio foley, and audio-driven lip synchronization.' },
  { id: 'render-delivery', parent: 'postprod', level: 2, file: '62-delivery.js', color: 'orange',
    title: 'Compositing, Encoding & Streaming', kicker: 'Timeline to CDN',
    summary: 'Edit decision lists, frame interpolation and super-resolution, codecs (H.264 / HEVC / AV1), HLS/DASH ladders and CDN.' },

  { id: 'infra', parent: 'overview', level: 1, file: '70-infra.js', color: 'red',
    title: 'AI Infrastructure & GPU Cluster', kicker: 'Where the FLOPs live',
    summary: 'Control plane, schedulers, inference engines and thousands of interconnected GPUs serving LLM and video models.' },
  { id: 'scheduler', parent: 'infra', level: 2, file: '71-scheduler.js', color: 'red',
    title: 'GPU Cluster Scheduling', kicker: 'Queues, gangs, preemption',
    summary: 'Priority queues, gang scheduling, topology-aware bin packing, preemption, autoscaling and cold-start weight loading.' },
  { id: 'load-balancing', parent: 'infra', level: 2, file: '72-lb.js', color: 'red',
    title: 'Inference Load Balancing', kicker: 'Routing every request',
    summary: 'L4/L7 balancing, power-of-two-choices, KV-cache / prefix-aware routing, consistent hashing and SLO-aware admission.' },
  { id: 'llm-serving', parent: 'infra', level: 2, file: '73-llm-serving.js', color: 'red',
    title: 'LLM Serving Engine', kicker: 'Tokens per second per dollar',
    summary: 'Continuous batching, PagedAttention, prefix caching, prefill/decode disaggregation, quantization and speculative decoding.' },
  { id: 'video-serving', parent: 'infra', level: 2, file: '74-video-serving.js', color: 'red',
    title: 'Video Model Serving', kicker: 'Minutes of GPU per clip',
    summary: 'Sequence parallelism across GPUs, CFG parallelism, step caching, VAE tiling, few-step distilled students and job pipelines.' },
  { id: 'gpu', parent: 'infra', level: 2, file: '75-gpu.js', color: 'red',
    title: 'Inside the GPU & Interconnect', kicker: 'SMs, HBM, NVLink',
    summary: 'Streaming multiprocessors, tensor cores, memory hierarchy, roofline analysis, NVLink domains and RDMA fabrics.' },
  { id: 'parallelism', parent: 'infra', level: 2, file: '76-parallelism.js', color: 'red',
    title: 'Distributed Parallelism', kicker: 'DP · TP · PP · EP · SP',
    summary: 'How one model spans many GPUs: data, tensor, pipeline, expert and sequence parallelism, and the collectives that bind them.' },

  { id: 'data', parent: 'overview', level: 1, file: '80-data.js', color: 'teal',
    title: 'Data, Memory & Storage', kicker: 'State of the system',
    summary: 'Object storage for media, metadata databases, event logs, caches and the agent memory layer.' },
  { id: 'rag-memory', parent: 'data', level: 2, file: '81-rag.js', color: 'teal',
    title: 'Vector Memory & Retrieval', kicker: 'Embeddings + ANN',
    summary: 'Multimodal embeddings, HNSW graphs, hybrid search, reranking and long-term memory for characters and styles.' },

  { id: 'trust', parent: 'overview', level: 1, file: '90-trust.js', color: 'pink',
    title: 'Safety, Evaluation & Observability', kicker: 'Keeping it honest',
    summary: 'Guardrails and moderation, provenance, automatic evaluation, tracing and cost accounting across the whole pipeline.' },
  { id: 'safety', parent: 'trust', level: 2, file: '91-safety.js', color: 'pink',
    title: 'Guardrails & Provenance', kicker: 'Policy at every hop',
    summary: 'Input/output classifiers, prompt-injection defense for tool-using agents, watermarking and C2PA content credentials.' },
  { id: 'eval-obs', parent: 'trust', level: 2, file: '92-eval-obs.js', color: 'pink',
    title: 'Evals & Observability', kicker: 'Measure everything',
    summary: 'VBench-style and preference evals, LLM-as-judge critics, distributed tracing of agent runs, SLOs and cost per video.' }
];

/* Big-picture tour: L0 then the subsystems in request-lifecycle order. */
window.ATLAS_TOURS = {
  bigpicture: ['overview', 'client', 'gateway', 'orchestration', 'multimodal', 'llm', 'videogen', 'infra', 'postprod', 'data', 'trust'],
  deep: null /* computed: depth-first over the catalog */
};
